package fr.osallek.osasaveviewer.controller.dto.save;

public enum Losses {
    INFANTRY_FIGHT,
    INFANTRY_ATTRITION,
    INFANTRY_STEAL,
    CAVALRY_FIGHT,
    CAVALRY_ATTRITION,
    CAVALRY_STEAL,
    ARTILLERY_FIGHT,
    ARTILLERY_ATTRITION,
    ARTILLERY_STEAL,
    HEAVY_FIGHT,
    HEAVY_ATTRITION,
    HEAVY_STEAL,
    LIGHT_FIGHT,
    LIGHT_ATTRITION,
    LIGHT_STEAL,
    GALLEY_FIGHT,
    GALLEY_ATTRITION,
    GALLEY_STEAL,
    TRANSPORT_FIGHT,
    TRANSPORT_ATTRITION,
    TRANSPORT_STEAL
}
