package fr.osallek.osasaveviewer.controller.dto.save;

public enum PowerSpent {
    IDEAS(0),
    TECHNOLOGY(1),
    STABILITY(2),
    USELESS_BUY_GENERAL(3),
    USELESS_BUY_ADMIRAL(4),
    USELESS_BUY_CONQUISTADOR(5),
    USELESS_BUY_EXPLORER(6),
    DEVELOPMENT(7),
    USELESS_FORCE_MARCH(8),
    ASSAULTING(9),
    SEIZE_COLONY(10),
    BURN_COLONY(11),
    KILL_NATIVES(12),
    SCORCHING_EARTH(13),
    PEACE_DEAL(14),
    REDUCE_INFLATION(15),
    MOVE_CAPITAL(16),
    CORING(17),
    REMOVE_RIVALRY(18),
    USELESS_19(19),
    CULTURE_CONVERSION(20),
    HARSH_TREATMENT(21),
    REDUCING_WAR_EXHAUSTION(22),
    PROMOTE_FACTION(23),
    USELESS_24(24),
    INCREASE_TARIFFS(25),
    MERCANTILISM(26),
    DECREASE_TARIFFS(27),
    MOVE_TRADE_CAPITAL(28),
    CREATE_TRADE_POST(29),
    SORTIE_FROM_SIEGE(30),
    USELESS_31(31),
    SET_PRIMARY_CULTURE(32),
    PROMOTE_CULTURE(33),
    DEMOTE_CULTURE(34),
    STRENGTHEN_GOVERNMENT(35),
    MILITARIZATION(36),
    OTHER_37(37), //ADM DIP can be negative
    BARRAGING(38),
    SIBERIAN_FRONTIER(39),
    USELESS_40(40),
    BUILD_SUPPLY_DEPOT(41),
    NAVAL_BARRAGING(42),
    OTHER_44(44), //RECRUIT_JANISARIES ESTABLISH_HOLY_ORDER
    FORCING_MARCH(45),
    HIRING_GENERAL(46),
    FORCE_CULTURE(47);

    public final int index;

    PowerSpent(int index) {
        this.index = index;
    }
}
