import AbstractTemplate from "./AbstractTemplate";
export default ItemTemplate;
declare class ItemTemplate extends AbstractTemplate {
    constructor(options: any, config: any);
    options: any;
    config: any;
    styles: {
        defaultTemplate: {
            width: string;
            height: string;
            left: string;
            top: string;
            border: string;
            background: string;
            color: string;
            MozBorderRadius: string;
            WebkitBorderRadius: string;
            KhtmlBorderRadius: string;
            BorderRadius: string;
            position: string;
            overflow: string;
            fontFamily: string;
            WebkitTapHighlightColor: string;
            WebkitUserSelect: string;
            WebkitTouchCallout: string;
            KhtmlUserSelect: string;
            MozUserSelect: string;
            msUserSelect: string;
            userSelect: string;
            boxSizing: string;
        };
        title: {
            top: string;
            left: string;
            right: string;
            height: string;
            textOverflow: string;
            OTextOverflow: string;
            whiteSpace: string;
            textAlign: string;
            fontSize: string;
            lineHeight: string;
            color: string;
            padding: number;
            position: string;
            overflow: string;
            fontFamily: string;
            WebkitTapHighlightColor: string;
            WebkitUserSelect: string;
            WebkitTouchCallout: string;
            KhtmlUserSelect: string;
            MozUserSelect: string;
            msUserSelect: string;
            userSelect: string;
            boxSizing: string;
        };
        background: {
            top: string;
            left: string;
            right: string;
            height: string;
            border: string;
            background: string;
            color: string;
            MozBorderRadius: string;
            WebkitBorderRadius: string;
            KhtmlBorderRadius: string;
            BorderRadius: string;
            position: string;
            overflow: string;
            fontFamily: string;
            WebkitTapHighlightColor: string;
            WebkitUserSelect: string;
            WebkitTouchCallout: string;
            KhtmlUserSelect: string;
            MozUserSelect: string;
            msUserSelect: string;
            userSelect: string;
            boxSizing: string;
        };
        photoFrame: {
            top: string;
            left: string;
            width: string;
            height: string;
            border: string;
            background: string;
            color: string;
            position: string;
            overflow: string;
            fontFamily: string;
            WebkitTapHighlightColor: string;
            WebkitUserSelect: string;
            WebkitTouchCallout: string;
            KhtmlUserSelect: string;
            MozUserSelect: string;
            msUserSelect: string;
            userSelect: string;
            boxSizing: string;
        };
        photo: {
            height: string;
            width: string;
        };
        description: {
            overflow: string;
            textAlign: string;
            top: string;
            left: string;
            right: string;
            bottom: string;
            fontSize: string;
            position: string;
            fontFamily: string;
            WebkitTapHighlightColor: string;
            WebkitUserSelect: string;
            WebkitTouchCallout: string;
            KhtmlUserSelect: string;
            MozUserSelect: string;
            msUserSelect: string;
            userSelect: string;
            boxSizing: string;
        };
    };
}